language: rust
dist: focal
rust:
- nightly
install:
- rustup install stable
- rustup update
- rustup default nightly
- rustup component add clippy
- cargo install grcov rust-covfix
jobs:
  include:
  - stage: test and format check
    os: linux
    dist: focal
    before_script:
    - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu
    script:
    - cargo test --features excel
    - cargo clippy --features excel -Z unstable-options -- -D warnings
    - cargo +stable fmt --all -- --check
    - bash coverage.sh ontravis sendcov
  - stage: deploy (linux & windows)
    os: linux
    dist: focal
    if: tag IS present
    before_script:
    - sudo apt-get install -y mingw-w64 clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev
      libgmp-dev zip unzip
    - rustup target add x86_64-unknown-linux-gnu x86_64-pc-windows-gnu
    script:
    - cargo build --target x86_64-unknown-linux-gnu --release --features excel
    - cargo build --target x86_64-pc-windows-gnu --release --features excel
    - zip -j mddoc_x86_64-unknown-linux-gnu.zip "./target/x86_64-unknown-linux-gnu/release/mddoc"
    - zip -j mddoc_x86_64-pc-windows-gnu.zip "./target/x86_64-pc-windows-gnu/release/mddoc.exe"
    deploy:
    - provider: releases
      skip_cleanup: true
      on:
        tags: true
      api_key:
        secure: 5dcGGWEzZ/jj41rDkBLlNa5FMZh56NNsDcbe+OZ7fEWUcTWKQSYRQaQGYojgQa4rZbfiWWvhMP5sWdI2/Cy765Qw+6GOdvjALhxdkg6ybNQnYlb4NFX/XKzf26+ALfNOvdGtno4dey+yHrfV6jlODSBWz53EIBJja/BrFHLt6lgZhhsBVt97zxDppSospgBwCEmKH214/7At5G+pEi7mr7OjrDOkmYm9gobK2MdCzFbpirDcIWSYLUjnwjHJJ3833vBGfjrCIsFVE7W4ZJqzR7qMJZVxqwoQSKGiAqh2bkj5pPCekOEa63VcONgYuyJgvgza0dNY8fvPv9plpEC6x3BSxJWPBNp+BJCKlAqnNcQ7RlsY5IxEDwEHC0e33Yaxu7LLaDmzhDfHMaBT8i60s99JWcB/6aEQSWDyr9SPD1wiX36bZDFfd0UVtWb7xOpdCN8U6BAlGwhD7kNbDdvqJjBt9SQ3L2xdxkut1mNRBJQ0dJN2T3odAxyl7QuE8/xHDGEjFHlG9SylIvh0M9Wezv+DqUDXH1lH6qjwxG7KipAG7Kkqs4j37i6w9c+UXQH7uI/DYF27tCR9iLEf5oTguY0DIxN9+lRCSw/YUH1wW5/3v/MOvxtVt3k/7JYCsPZOa3g2VJ4rblMSVl+pJsQQCO+sm8yGvDUov1K/c5PItec=
      file:
      - mddoc_x86_64-unknown-linux-gnu.zip
      - mddoc_x86_64-pc-windows-gnu.zip
  - stage: deploy (mac)
    os: osx
    if: tag IS present
    before_script:
    - brew install zip
    script:
    - cargo build --target x86_64-apple-darwin --release --features excel
    - zip -j mddoc_x86_64-apple-darwin.zip "./target/x86_64-apple-darwin/release/mddoc"
    deploy:
    - provider: releases
      skip_cleanup: true
      on:
        tags: true
      api_key:
        secure: 5dcGGWEzZ/jj41rDkBLlNa5FMZh56NNsDcbe+OZ7fEWUcTWKQSYRQaQGYojgQa4rZbfiWWvhMP5sWdI2/Cy765Qw+6GOdvjALhxdkg6ybNQnYlb4NFX/XKzf26+ALfNOvdGtno4dey+yHrfV6jlODSBWz53EIBJja/BrFHLt6lgZhhsBVt97zxDppSospgBwCEmKH214/7At5G+pEi7mr7OjrDOkmYm9gobK2MdCzFbpirDcIWSYLUjnwjHJJ3833vBGfjrCIsFVE7W4ZJqzR7qMJZVxqwoQSKGiAqh2bkj5pPCekOEa63VcONgYuyJgvgza0dNY8fvPv9plpEC6x3BSxJWPBNp+BJCKlAqnNcQ7RlsY5IxEDwEHC0e33Yaxu7LLaDmzhDfHMaBT8i60s99JWcB/6aEQSWDyr9SPD1wiX36bZDFfd0UVtWb7xOpdCN8U6BAlGwhD7kNbDdvqJjBt9SQ3L2xdxkut1mNRBJQ0dJN2T3odAxyl7QuE8/xHDGEjFHlG9SylIvh0M9Wezv+DqUDXH1lH6qjwxG7KipAG7Kkqs4j37i6w9c+UXQH7uI/DYF27tCR9iLEf5oTguY0DIxN9+lRCSw/YUH1wW5/3v/MOvxtVt3k/7JYCsPZOa3g2VJ4rblMSVl+pJsQQCO+sm8yGvDUov1K/c5PItec=
      file:
      - mddoc_x86_64-apple-darwin.zip
  - stage: deploy (crates.io)
    os: linux
    dist: focal
    if: tag IS present
    script:
      - cargo publish --features excel --token ${CRATES_IO_TOKEN}
env:
  global:
  - secure: zOr7Re70susrc/q7/nVwcorOexfBFBuJx/dztkt0VwXfAxTic3SlK38wMBJ9vOH+OOMuqYp9mjhKjJaBMsTw2wja93dh6KzaEiUsb9RQjBSdZlutWfrlDhkZSLr5dZjRzB2rnaIYKdaKCDEz4TVtoGAeTjuNSiLxxE0l6RFawl+ekhKqCYmbyyUzZdCQPPS0lthcJxhRnLZmeY1ojM5dbdgBubHhQ9ksCPVn+1GlwO8fkW8RlNgeWbtim1EsIMmsozRDGYmyPtWKYjJVBey49iindZnmSzaKJ0ilbQX2HwjYshaD+kauOXgQz/wZd0FwRdiqtvDpzwSkW+SGVYcs59dKJoDXVpiqypTWJ0k+jRGEdeR0Kq40sKmPsjk5yNMQr/Sy5fLDYHWnUAW9VUzZdFIc8lKZwXU/ez3QbCErfYW4RVaKHyrxjkQ9rRbSjTCRXHDILs/nF9E58NP/AV6noPkygCyzHhArvU1/q+DB/rg4q1H6XqTsX5LFjJzbh6hJnq4PHmEmhIVC5XIGe9rnLyD7VPdkwlsUXWYnQSnnSfc7m0vyZ8sqonR/r/d09kIHyUzZWOEhnfssB1IEdlKsTvL60xdDYmUX0E1/v98cuu4TwgHYszOSMZwGuTyCfkg+FCMTROmEQG/QZXHZ/uDTgCoEGLWrV09WiPWl0xEO9ms=
  - secure: T0HTmgfW6lPMyF9nl00CBs+R+Jt+k1yw9RFwRrN2H62PuG7Vqct2J48AJpSJtJL83Zh/2X4NVBw90waecPKoJNgdXXLLBPgn/spM+yV0sc53nrMzwVm4aUvoCSkdvkJO9byRwu4cXTkHDn7A8BAunI/TiHTo+h/2zuZN8d+w9RZXx2VTR9ZPD+uQn9zyLBDu26lUW7+C9BwVnVdaI0rXpOlUvCOibk6c+jjKQP/SjKeBCFoQTUdGwYAkF4IDCBepZwijd1zXUg4FBy6xyabVFXaXKHDxCCt41zE9EoeRHa+A33YdwiRUH+L4AA8tWR5meewJ47SC6wUPoifHluyZOLTdufZt3bIpkH3WmxZFLv3uZLVsnQ9oOAHbMrUQ0Jg/U4FX+b1jaqZ9gy06wl+mCFCEN0cKs94rbkfNvA3aeK2w4iYL+tC9JIDRbQ7It0Du83UrawdZTgfISq8EeeeTMvobQg3nSlpWkQZdOAHM3g27Op0Q1PCweKdo5PT8lbnweaabKn0hD/JntP82rzCT+WBRCE+7EOBRDJY62IUNh2CxgEj3qa+ajfL9QVCQk5bRz5F2j/suN/gjNHupFlGl6NszI+JVhEYNy/5G5VRMt0ULOjyJwmnOMsNPexNaqmxp0te5q8z2NaPK0ghR/KlCEXOsGdYuWdQQNXGM+fV/ynQ=
